version: 2

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - "-X github.com/aspettl/ccliwrapper/cmd.Version={{ .Version }}"
archives:
  - name_template: >-
      {{- .ProjectName }}_
      {{- .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end -}}
    files:
      - README.md
      - LICENSE
      - example/**
dockers_v2:
  - dockerfile: Dockerfile.goreleaser
    images:
      - "{{ .Env.DOCKERHUB_USERNAME }}/{{ .ProjectName }}"
    tags:
      - "{{ .Version }}"
      - "latest"
    labels:
      "org.opencontainers.image.title": "{{.ProjectName}}"
      "org.opencontainers.image.url": "{{.GitURL}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.licenses": "MIT"
    platforms:
      - linux/amd64
      - linux/arm64
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
